export const ROOMS_DATA = [
    { id: 1, name: "Sea View Suite", price: 120.5, isAvailable: true, ratingInfo: { rating: 4.5, reviewCount: 150 } },
    { id: 2, name: "Mountain Cabin", price: 85.0, isAvailable: false, ratingInfo: { rating: 4.0, reviewCount: 200 } },
    { id: 3, name: "City Center Studio", price: 95.0, isAvailable: true, ratingInfo: { rating: 4.7, reviewCount: 320 } },
    { id: 4, name: "Luxury Penthouse", price: 250.0, isAvailable: true, ratingInfo: { rating: 4.8, reviewCount: 75 } },
    { id: 5, name: "Garden View Room", price: 110.0, isAvailable: true, ratingInfo: { rating: 4.3, reviewCount: 110 } },
    { id: 6, name: "Beachfront Bungalow", price: 140.0, isAvailable: false, ratingInfo: { rating: 4.9, reviewCount: 45 } },
    { id: 7, name: "Suburban Suite", price: 95.0, isAvailable: true, ratingInfo: { rating: 3.8, reviewCount: 98 } },
    { id: 8, name: "Modern Loft", price: 105.0, isAvailable: false, ratingInfo: { rating: 4.2, reviewCount: 180 } },
    { id: 9, name: "Downtown Apartment", price: 120.0, isAvailable: true, ratingInfo: { rating: 4.6, reviewCount: 220 } },
    { id: 10, name: "Country House", price: 80.0, isAvailable: true, ratingInfo: { rating: 3.9, reviewCount: 160 } },
    { id: 11, name: "Skyline View Suite", price: 160.0, isAvailable: true, ratingInfo: { rating: 4.4, reviewCount: 140 } },
    { id: 12, name: "Riverside Retreat", price: 130.0, isAvailable: false, ratingInfo: { rating: 4.7, reviewCount: 190 } },
    { id: 13, name: "Cozy Studio", price: 70.0, isAvailable: true, ratingInfo: { rating: 3.5, reviewCount: 210 } },
    { id: 14, name: "Executive Suite", price: 180.0, isAvailable: false, ratingInfo: { rating: 4.3, reviewCount: 130 } },
    { id: 15, name: "Alpine Chalet", price: 95.0, isAvailable: true, ratingInfo: { rating: 4.1, reviewCount: 160 } },
    { id: 16, name: "Seaside Room", price: 110.0, isAvailable: true, ratingInfo: { rating: 4.6, reviewCount: 240 } },
    { id: 17, name: "Mansion Suite", price: 300.0, isAvailable: true, ratingInfo: { rating: 4.9, reviewCount: 50 } },
    { id: 18, name: "Forest Cabin", price: 85.0, isAvailable: false, ratingInfo: { rating: 3.7, reviewCount: 220 } },
    { id: 19, name: "Downtown Loft", price: 125.0, isAvailable: true, ratingInfo: { rating: 4.5, reviewCount: 210 } },
    { id: 20, name: "Luxury Villa", price: 220.0, isAvailable: true, ratingInfo: { rating: 4.8, reviewCount: 60 } },
    { id: 21, name: "Oceanfront Cabin", price: 130.0, isAvailable: false, ratingInfo: { rating: 4.4, reviewCount: 180 } },
    { id: 22, name: "City Penthouse", price: 170.0, isAvailable: true, ratingInfo: { rating: 4.7, reviewCount: 140 } },
    { id: 23, name: "Art Deco Studio", price: 105.0, isAvailable: true, ratingInfo: { rating: 4.3, reviewCount: 170 } },
    { id: 24, name: "Suburban House", price: 90.0, isAvailable: true, ratingInfo: { rating: 3.8, reviewCount: 200 } },
    { id: 25, name: "Skyview Suite", price: 200.0, isAvailable: true, ratingInfo: { rating: 4.9, reviewCount: 40 } },
    { id: 26, name: "Eco Lodge", price: 75.0, isAvailable: false, ratingInfo: { rating: 4.1, reviewCount: 250 } },
    { id: 27, name: "Private Villa", price: 160.0, isAvailable: true, ratingInfo: { rating: 4.5, reviewCount: 210 } },
    { id: 28, name: "Penthouse Loft", price: 220.0, isAvailable: false, ratingInfo: { rating: 4.6, reviewCount: 130 } },
    { id: 29, name: "Beach House", price: 180.0, isAvailable: true, ratingInfo: { rating: 4.2, reviewCount: 190 } },
    { id: 30, name: "Downtown Studio", price: 85.0, isAvailable: true, ratingInfo: { rating: 4.0, reviewCount: 180 } },
    { id: 31, name: "Mountain View Room", price: 110.0, isAvailable: false, ratingInfo: { rating: 4.3, reviewCount: 210 } },
    { id: 32, name: "Sky Tower Suite", price: 240.0, isAvailable: true, ratingInfo: { rating: 4.7, reviewCount: 130 } },
    { id: 33, name: "Riverbank Retreat", price: 130.0, isAvailable: true, ratingInfo: { rating: 4.4, reviewCount: 220 } },
    { id: 34, name: "City Loft", price: 115.0, isAvailable: true, ratingInfo: { rating: 4.2, reviewCount: 210 } },
    { id: 35, name: "Urban Retreat", price: 150.0, isAvailable: false, ratingInfo: { rating: 4.0, reviewCount: 180 } },
    { id: 36, name: "Luxury Garden Suite", price: 175.0, isAvailable: true, ratingInfo: { rating: 4.8, reviewCount: 90 } },
    { id: 37, name: "Coastal Cottage", price: 100.0, isAvailable: true, ratingInfo: { rating: 3.9, reviewCount: 220 } },
    { id: 38, name: "Woodland Lodge", price: 85.0, isAvailable: true, ratingInfo: { rating: 4.1, reviewCount: 180 } },
    { id: 39, name: "Ocean Breeze Room", price: 120.0, isAvailable: false, ratingInfo: { rating: 4.6, reviewCount: 150 } },
    { id: 40, name: "Country Estate", price: 140.0, isAvailable: true, ratingInfo: { rating: 4.4, reviewCount: 170 } },
    { id: 41, name: "Beachfront Penthouse", price: 230.0, isAvailable: true, ratingInfo: { rating: 4.8, reviewCount: 50 } },
    { id: 42, name: "Artistic Loft", price: 90.0, isAvailable: true, ratingInfo: { rating: 4.0, reviewCount: 200 } },
    { id: 43, name: "Central Park Suite", price: 150.0, isAvailable: true, ratingInfo: { rating: 4.3, reviewCount: 170 } },
    { id: 44, name: "Mountain Lodge", price: 95.0, isAvailable: false, ratingInfo: { rating: 4.2, reviewCount: 150 } },
    { id: 45, name: "Beach House", price: 170.0, isAvailable: true, ratingInfo: { rating: 4.7, reviewCount: 90 } },
    { id: 46, name: "Seaside Loft", price: 140.0, isAvailable: true, ratingInfo: { rating: 4.5, reviewCount: 180 } },
    { id: 47, name: "Mountain View Lodge", price: 105.0, isAvailable: true, ratingInfo: { rating: 4.1, reviewCount: 160 } },
    { id: 48, name: "Downtown Penthouse", price: 200.0, isAvailable: true, ratingInfo: { rating: 4.9, reviewCount: 80 } },
    { id: 49, name: "Cozy Mountain Cabin", price: 90.0, isAvailable: false, ratingInfo: { rating: 4.3, reviewCount: 120 } },
    { id: 50, name: "Grand Hotel Suite", price: 300.0, isAvailable: true, ratingInfo: { rating: 4.6, reviewCount: 200 } }
]

